### ISSUE TITLE
Add navigation on signup/signin page

### ISSUE THREAD

**Issue by ShauryaSood2003** [ShauryaSood2003/CodeCrack#1]
Use the react-router-dom npm package to add a small button/Link that allows users to navigate between the signin and signup pages for both user and admin. This task is fairly simple and the package is already installed in the project. You can find the signin and signup components here: [https://github.com/ShauryaSood2003/CodeCrack/tree/main/frontEnd/src/components](url)

**Comment by kagrawal29** [comment]
Can you assign this issue? I have decent experience working with frontend components in react

**Comment by ShauryaSood2003** [comment]
> Can you assign this issue? I have decent experience working with frontend components in react

Bro, the issue has already been solved . I will be adding some UI issues in the future, so stay tuned!

**Comment by ShauryaSood2003** [comment]
Shoutout to @tushar-2811 for the quick resolution! The issue is now solved.
