### ISSUE TITLE
Difficulty tag is colourless

### ISSUE THREAD

**Issue by tushar-2811** [ShauryaSood2003/CodeCrack#5]
Difficulty Tag is Colourless.

description:
Every problem has an associated difficulty level tag , which is either easy , medium or hard , the tag don't have any bg-color

To Reproduce:
1 . Sign In using credentials.
2. Select the Go to problems button from header , after login.
3. Select a problem to solve
4. See the colorless difficulty tags

![Screenshot 2024-05-23 155042](https://github.com/ShauryaSood2003/CodeCrack/assets/95456830/61273667-628f-4784-b27c-52672acd9bd8)

Expected Behaviour:
The tags should be colored , easy tag should have bg-green , medium tag should have bg-orange , hard tag should have bg-red.

**Comment by ShauryaSood2003** [comment]
they are colored but very light colored in light mode
![Screenshot 2024-05-24 131828](https://github.com/ShauryaSood2003/CodeCrack/assets/98689480/c7180e34-93c0-4eff-ac21-7d36c9c545e5)
![Screenshot 2024-05-24 131836](https://github.com/ShauryaSood2003/CodeCrack/assets/98689480/d942e5cf-ef01-4cea-91ce-bb7dfeaf8a64)
